theme: minima
title: Machine Learning in Forensic Genetics
author: Miray Özmutlu
description: This blog site will consist of discussions and easy-to-digest forms of communication regarding the use of machine learning in forensic genetics. 
